#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Gradle daemon memory
org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8

# Enable parallel compilation for faster builds
org.gradle.parallel=true

# Optional: configure Kotlin/Native memory (for iOS builds)
kotlin.native.cacheKind=dynamic